#!/usr/bin/env bash
ln -sf RP2350/{*.ml{,i},libmincaml.S} .
cd test; ln -sf RP2350/{,too}manyargs.ml .; cd ..
cd shootout; ln -sf RP2350/Makefile .; cd ..
cd bytemark; ln -sf RP2350/Makefile .; cd ..
cd min-rt; ln -sf RP2350/globals.s .; cd ..
